### ISSUE TITLE
Got an error when execute "cargo install ncmdump"

### ISSUE THREAD

**Issue by yudshj** [lucifer9/ncmdump-rust#1]
```
error: failed to compile `ncmdump v0.1.0`, intermediate artifacts can be found at `/var/folders/fl/tgg878051bbd2_6lktghsj5m0000gn/T/cargo-installPlBp6v`

Caused by:
  failed to select a version for the requirement `aes = "^0.3.2"`
  candidate versions found which didn't match: 0.7.5, 0.7.4, 0.7.3, ...
  location searched: crates.io index
  required by package `ncmdump v0.1.0`
```

**Comment by lucifer9** [comment]
Sorry, but the one with the same name you found on [crates.io](https://crates.io/crates/ncmdump) is NOT this one. You can open an issue at https://github.com/anonymous5l/ncmdump.

However, if you want to try mine, just `git clone https://github.com/lucifer9/ncmdump-rust`, then `cd ncmdump-rust`, then `cargo build --release`. You can find the binary in `target/release/`. I just updated the dependencies and verified that it builds successfully on linux and macOS.

**Comment by yudshj** [comment]
It works! Thanks a lot!
